"""Baseline schema — create all current tables.

This captures the full present schema (including the screener feature columns:
iv_rank, vol_oi, is_opening, days_to_earnings, bullish_structure,
follow_through, ticker_hit_rate). A fresh database reaches the current schema
with ``alembic upgrade head``; future changes get their own autogenerated
revisions instead of wiping the volume.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-22
"""
from typing import Sequence, Union

from alembic import op

import app.db.models  # noqa: F401 — register tables on Base.metadata
from app.db.base import Base

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
