"""Scoring consumer — the event-driven worker.

Consumes normalised events from the Redis Stream (consumer group), enriches +
scores them, writes results in **batches** (one transaction per batch instead
of per event — the main DB-write optimisation), publishes to the live channel,
fires alerts, then acks. Scale by running N replicas in the same group.
"""
from __future__ import annotations

import asyncio
import time

from app.alerts.base import AlertDispatcher
from app.alerts.summary import generate_summary
from app.core.logging import get_logger
from app.core.queue import ack, consume, reclaim_stale
from app.core.redis_client import FLOW_CHANNEL, publish
from app.db.base import SessionLocal
from app.db.models import Alert, FlowFeatures, FlowScore, RawFlow
from app.pipeline.realtime import (
    FollowThroughTracker,
    IVRankTracker,
    SweepTracker,
    flow_payload,
)
from app.scoring.sequence import SequenceTracker
from app.providers.polygon import PolygonContextProvider
from app.providers.regime import RegimeProvider
from app.schemas.flow import FlowEvent, FlowFeatureVector, ScoreResult
from app.scoring.classifier import classify

log = get_logger("consumer")

GROUP = "scorers"
FLUSH_SIZE = 50
FLUSH_INTERVAL = 1.0  # seconds — bound alert latency

_FEATURE_COLS = (
    "ask_side_ratio", "sweep_urgency", "repeated_sweeps", "at_midpoint",
    "otm_pct", "dte", "rel_options_volume", "stock_rvol", "oi_change_ratio",
    "float_shares", "short_interest_pct", "borrow_rate", "dealer_gamma",
    "iv_rank", "vol_oi", "is_opening", "days_to_earnings", "bullish_structure",
    "follow_through", "ticker_hit_rate",
    "social_score", "news_score", "historical_similarity",
)


class BatchWriter:
    """Buffers scored events and flushes them in a single transaction.

    Inserts all RawFlow rows, flushes once to get autogenerated ids, then bulk
    inserts the dependent feature/score rows. Returns the assigned flow_ids in
    submission order so the caller can publish/alert with real ids.
    """

    def __init__(self):
        self._buf: list[tuple[FlowEvent, FlowFeatureVector, ScoreResult]] = []

    def add(self, event, features, result) -> None:
        self._buf.append((event, features, result))

    def __len__(self) -> int:
        return len(self._buf)

    async def flush(self) -> list[tuple[int, FlowEvent, FlowFeatureVector, ScoreResult]]:
        if not self._buf:
            return []
        batch, self._buf = self._buf, []
        async with SessionLocal() as session:
            raws = [
                RawFlow(
                    source=e.source, external_id=e.external_id, ticker=e.ticker,
                    contract_type=e.contract_type.value, strike=e.strike, expiry=e.expiry,
                    side=e.side.value if e.side else None, is_sweep=e.is_sweep,
                    is_spread=e.is_spread, premium=e.premium, size=e.size, spot=e.spot,
                    raw=e.raw, observed_at=e.observed_at,
                )
                for e, _, _ in batch
            ]
            session.add_all(raws)
            await session.flush()   # one round-trip -> all ids populated

            for raw, (e, feats, res) in zip(raws, batch):
                session.add(FlowFeatures(
                    flow_id=raw.id, vector=feats.model_dump(),
                    **{k: getattr(feats, k) for k in _FEATURE_COLS},
                ))
                session.add(FlowScore(
                    flow_id=raw.id, classification=res.classification.value,
                    confidence=res.confidence, explosion_prob=res.explosion_prob,
                    squeeze_prob=res.squeeze_prob, momentum_prob=res.momentum_prob,
                    fake_flow_prob=res.fake_flow_prob,
                    component_scores=res.component_scores,
                    reasons={"reasons": res.reasons}, regime=res.regime,
                    model_version=res.model_version,
                ))
            await session.commit()
            return [(raw.id, e, feats, res) for raw, (e, feats, res) in zip(raws, batch)]


class ScoringConsumer:
    def __init__(self, name: str):
        self.name = name
        self.context = PolygonContextProvider()
        self.regime_provider = RegimeProvider()
        self.dispatcher = AlertDispatcher()
        self.sweeps = SweepTracker()
        self.sequences = SequenceTracker()
        self.iv_ranks = IVRankTracker()
        self.follow = FollowThroughTracker()
        self.writer = BatchWriter()
        self._pending_ids: list[str] = []
        self._last_flush = time.monotonic()

    async def _flush(self) -> None:
        written = await self.writer.flush()
        for flow_id, event, features, result in written:
            await publish(FLOW_CHANNEL, flow_payload(flow_id, event, result))
            if self.dispatcher.should_alert(result, event, features):
                channels = await self.dispatcher.dispatch(event, result)
                await self._record_alert(flow_id, event, result, channels)
        if self._pending_ids:
            await ack(GROUP, *self._pending_ids)
            self._pending_ids = []
        self._last_flush = time.monotonic()

    async def _record_alert(self, flow_id, event, result, channels) -> None:
        async with SessionLocal() as session:
            session.add(Alert(
                flow_id=flow_id, ticker=event.ticker,
                classification=result.classification.value, confidence=result.confidence,
                summary=generate_summary(event, result), channels=channels,
            ))
            await session.commit()

    async def handle(self, msg_id: str, data: dict) -> None:
        event = FlowEvent(**data)
        ctx = await self.context.get_context(event.ticker)
        regime = await self.regime_provider.get_regime()
        repeated = self.sweeps.record(event)
        seq = self.sequences.record(event)
        iv_rank = self.iv_ranks.record(event)
        follow = self.follow.record(event)
        features, result = classify(event, ctx, repeated_sweeps=repeated,
                                    regime=regime, seq=seq,
                                    follow_through=follow, iv_rank=iv_rank)
        self.writer.add(event, features, result)
        self._pending_ids.append(msg_id)

    async def run(self) -> None:
        log.info("consumer starting", name=self.name, group=GROUP)
        # Recover anything a dead replica left pending.
        for msg_id, data in await reclaim_stale(GROUP, self.name):
            await self.handle(msg_id, data)

        async for msg_id, data in consume(GROUP, self.name, block_ms=1000):
            try:
                await self.handle(msg_id, data)
            except Exception as exc:  # noqa: BLE001 — never let one event kill the loop
                log.error("handle failed", msg_id=msg_id, error=str(exc))
                await ack(GROUP, msg_id)  # poison-pill: ack + drop (or route to DLQ)
            if len(self.writer) >= FLUSH_SIZE or \
                    time.monotonic() - self._last_flush >= FLUSH_INTERVAL:
                await self._flush()
